name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pdm install -G test

    - name: Run tests
      run: |
        pdm run -v pytest --doctest-modules
