name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04

    steps:
    - name: Check out the repository
      uses: actions/checkout@v7

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pdm install -G test

    # Update output format to enable automatic inline annotations.
    - name: Run Ruff
      run: pdm run ruff check --output-format=github .

    - name: Run tests
      run: |
        pdm run -v pytest --cov=QuantSI --cov-report lcov --doctest-modules

    - name: Publish coverage
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329  # v2.3.8
      with:
        format: lcov